'use strict';
(()=>{
const $=id=>document.getElementById(id),E=FlyEngine,C=E.CONFIG,fmt=n=>n.toLocaleString('es-ES');
const gameCanvas=$('game'),ctx=gameCanvas.getContext('2d'),net=$('network').getContext('2d'),chart=$('chart').getContext('2d');
let best=Array(17).fill(0),pending=null,game=new E.Game(4001),brain=new E.Brain(),flight=1,record=0,baseline=false,training=true,generation=0,episodes=0,history=[],baselineStats=null,lastReport=null,deadAt=0,last=0,acc=0,worldTime=0,saved=null;
const KEY='fruitfly-flappy-v1-'+E.circuit.fingerprint;
try{const parsed=JSON.parse(localStorage.getItem(KEY)||'null');if(parsed&&Array.isArray(parsed.weights)&&parsed.weights.length===17&&parsed.weights.every(Number.isFinite)){saved=parsed;best=parsed.weights;generation=parsed.generation||0;history=parsed.history||[];$('controller').textContent='Controlador guardado';}}catch(e){$('saving').textContent='El navegador no permite guardar aquí. Puedes descargar el controlador.';}
$('edgeCount').textContent=fmt(E.circuit.edges.length);
let worker;try{worker=new Worker('flappy-worker.js');}catch(e){$('status').textContent='Abre con jugar-flappy.cmd';return;}
const generationOffset=generation;
function save(){try{localStorage.setItem(KEY,JSON.stringify({weights:best,generation,history:history.slice(-200)}));}catch(e){$('saving').textContent='No se pudo guardar automáticamente. Usa Guardar controlador.';}}
worker.onmessage=({data:m})=>{if(m.type==='ready'){baselineStats=m.baseline;if(saved)worker.postMessage({type:'restore',weights:best});worker.postMessage({type:'start'});$('status').textContent='Aprendiendo en segundo plano';}
else if(m.type==='generation'){generation=m.generation+generationOffset;episodes=m.episodes;best=m.weights;pending=best;lastReport=m;history.push({generation,test:m.test,train:m.train});history=history.slice(-200);$('generation').textContent=generation;$('episodes').textContent=fmt(Math.round(episodes*78/81));$('testScore').textContent=m.test.toFixed(1);$('evaluation').textContent=`Sin entrenar: ${baselineStats.score.toFixed(1)} tubos · Controlador actual: ${m.test.toFixed(1)} tubos · Mismos 3 recorridos de evaluación`;$('status').textContent=training?'Aprendiendo · nuevo controlador disponible':'Terminando la generación actual';save();}
else if(m.type==='paused')$('status').textContent='Aprendizaje pausado · la mosca sigue volando';else if(m.type==='error'){$('status').textContent='Error de entrenamiento: '+m.message;training=false;}};
worker.onerror=e=>{$('status').textContent='No se pudo cargar el entrenamiento. Abre jugar-flappy.cmd.';training=false;};
let activeWeights=best.slice();
function newFlight(same=false){if(!same)flight++;game=new E.Game(4000+(same?flight:flight));brain=new E.Brain();activeWeights=(baseline?Array(17).fill(0):best).slice();pending=null;deadAt=0;$('flight').textContent=`Vuelo ${flight}`;$('controller').textContent=baseline?'Sin entrenar':generation?`Controlador · generación ${generation}`:'Sin entrenar';}
$('train').onclick=()=>{training=!training;worker.postMessage({type:training?'start':'pause'});$('train').textContent=training?'Ⅱ Pausar aprendizaje':'▶ Continuar aprendizaje';$('status').textContent=training?'Aprendiendo en segundo plano':'Pausa solicitada · termina esta generación';};
$('baseline').onclick=()=>{baseline=!baseline;$('baseline').textContent=baseline?'Ver controlador aprendido':'Ver sin entrenar';$('replayLabel').textContent=baseline?'COMPARACIÓN · SIN ENTRENAR':'EN VIVO · CONTROLADOR ACTUAL';newFlight(true);};
$('restartFlight').onclick=()=>newFlight(true);
$('reset').onclick=()=>{worker.terminate();try{localStorage.removeItem(KEY);}catch(e){}location.reload();};
$('download').onclick=()=>{const obj={schema:1,weights:best,circuitFingerprint:E.circuit.fingerprint,generation,history,model:E.circuit.model,validation:lastReport?.testRuns||[],baseline:baselineStats};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(obj,null,2)],{type:'application/json'}));a.download='fruitfly-controlador.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);};
function fit(canvas,context){const dpr=Math.min(devicePixelRatio||1,2),w=canvas.clientWidth,h=canvas.clientHeight;if(canvas.width!==Math.round(w*dpr)||canvas.height!==Math.round(h*dpr)){canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);}context.setTransform(canvas.width/w,0,0,canvas.height/h,0,0);return[w,h];}
function rounded(x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r);}
function drawFly(x,y,t){ctx.save();ctx.translate(x,y);ctx.rotate(Math.max(-.5,Math.min(.8,game.vy*.065)));ctx.shadowColor='#75f9d0';ctx.shadowBlur=12;ctx.fillStyle='#c1e5e8';ctx.globalAlpha=.7;const wing=Math.sin(t*.055)*.65;ctx.save();ctx.rotate(-.8+wing);ctx.beginPath();ctx.ellipse(-5,-11,15,6,0,0,Math.PI*2);ctx.fill();ctx.restore();ctx.save();ctx.rotate(.5-wing);ctx.beginPath();ctx.ellipse(-4,-12,14,5,0,0,Math.PI*2);ctx.fill();ctx.restore();ctx.globalAlpha=1;ctx.shadowBlur=0;ctx.fillStyle='#667f80';ctx.beginPath();ctx.ellipse(-8,3,13,8,.15,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#263a42';ctx.lineWidth=2;for(let i=-13;i<0;i+=4){ctx.beginPath();ctx.moveTo(i,-2);ctx.lineTo(i+2,8);ctx.stroke();}ctx.fillStyle='#aac4b6';ctx.beginPath();ctx.ellipse(2,0,8,9,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#ec796e';ctx.beginPath();ctx.arc(8,-1,6,0,Math.PI*2);ctx.fill();ctx.fillStyle='#ffd6ae';ctx.beginPath();ctx.arc(10,-3,2,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#bbd0bf';ctx.lineWidth=1;for(const offset of [-6,0,6]){ctx.beginPath();ctx.moveTo(offset,5);ctx.lineTo(offset-5,13);ctx.lineTo(offset-1,15);ctx.stroke();}ctx.restore();}
function drawGame(now){fit(gameCanvas,ctx);ctx.scale(gameCanvas.clientWidth/C.width,gameCanvas.clientHeight/C.height);const gradient=ctx.createLinearGradient(0,0,0,C.height);gradient.addColorStop(0,'#122c40');gradient.addColorStop(1,'#163b45');ctx.fillStyle=gradient;ctx.fillRect(0,0,C.width,C.height);
ctx.fillStyle='#89cfbd';for(let i=0;i<40;i++){const x=(i*157.31-worldTime*.008)%940;const y=40+(i*89.17)%390;ctx.globalAlpha=.08+(i%3)*.06;ctx.beginPath();ctx.arc(x<0?x+940:x,y,1+(i%2),0,Math.PI*2);ctx.fill();}ctx.globalAlpha=1;
for(let layer=0;layer<3;layer++){ctx.fillStyle=['#183b46','#1b434a','#21504e'][layer];ctx.beginPath();ctx.moveTo(0,C.floor);for(let x=0;x<=920;x+=20){const y=C.floor-35-layer*10-Math.sin((x+worldTime*.012*(layer+1))/110)*17-Math.sin(x/44+layer)*8;ctx.lineTo(x,y);}ctx.lineTo(920,C.floor);ctx.fill();}
const target=game.next();ctx.setLineDash([4,7]);ctx.strokeStyle='#a9e6c022';ctx.beginPath();ctx.moveTo(C.birdX,target.gapY);ctx.lineTo(Math.max(C.birdX,target.x),target.gapY);ctx.stroke();ctx.setLineDash([]);
for(const p of game.pipes){const top=p.gapY-C.gap/2,bottom=p.gapY+C.gap/2;const g=ctx.createLinearGradient(p.x,0,p.x+C.pipeWidth,0);g.addColorStop(0,'#31736e');g.addColorStop(.4,'#4f9c85');g.addColorStop(1,'#255b59');ctx.fillStyle=g;ctx.fillRect(p.x,0,C.pipeWidth,top);ctx.fillRect(p.x,bottom,C.pipeWidth,C.floor-bottom);ctx.fillStyle='#7db99a';rounded(p.x-5,top-15,C.pipeWidth+10,15,3);ctx.fill();rounded(p.x-5,bottom,C.pipeWidth+10,15,3);ctx.fill();ctx.strokeStyle='#94c9a94a';ctx.lineWidth=1;ctx.strokeRect(p.x+7,0,1,Math.max(0,top-15));ctx.strokeRect(p.x+7,bottom+15,1,C.floor-bottom-15);}
ctx.fillStyle='#18302f';ctx.fillRect(0,C.floor,C.width,50);ctx.fillStyle='#6a9d79';ctx.fillRect(0,C.floor,C.width,3);ctx.fillStyle='#476d54';for(let x=-20;x<920;x+=20){const xx=x-(worldTime*.04)%20;ctx.beginPath();ctx.moveTo(xx,C.floor);ctx.lineTo(xx+6,C.floor-7);ctx.lineTo(xx+13,C.floor);ctx.fill();}
drawFly(C.birdX,Math.max(12,Math.min(C.floor-12,game.y)),now);ctx.textAlign='center';ctx.font='600 52px Segoe UI';ctx.fillStyle='#e5f6e9';ctx.shadowColor='#0005';ctx.shadowBlur=10;ctx.fillText(game.score,C.width/2,77);ctx.shadowBlur=0;ctx.font='10px Segoe UI';ctx.fillStyle='#92b8ba';ctx.fillText('TUBOS SUPERADOS',C.width/2,98);
if(!game.alive){ctx.fillStyle='#091922bb';rounded(300,200,300,116,12);ctx.fill();ctx.fillStyle='#d7eee3';ctx.font='500 22px Segoe UI';ctx.fillText(game.won?'¡Recorrido completado!':'Otro intento, más experiencia.',450,241);ctx.font='12px Segoe UI';ctx.fillStyle='#8dbeb6';ctx.fillText(`${game.score} tubos · ${generation? 'probando el controlador aprendido':'explorando cómo aletear'}`,450,271);ctx.fillText('El siguiente vuelo empieza enseguida',450,294);}
}
const nodePositions=E.circuit.nodes.map((n,i)=>{const group=i%8,angle=i*2.39996;return[.12+group/7*.76,.5+Math.sin(angle)*(.13+(i%7)*.025)];});
function drawNetwork(){const[w,h]=fit($('network'),net);net.clearRect(0,0,w,h);net.strokeStyle='#5baca01c';net.lineWidth=.5;for(let k=0;k<E.circuit.edges.length;k+=11){const[a,b]=E.circuit.edges[k],p=nodePositions[a],q=nodePositions[b];net.beginPath();net.moveTo(p[0]*w,p[1]*h);net.lineTo(q[0]*w,q[1]*h);net.stroke();}nodePositions.forEach((p,i)=>{const value=Math.abs(brain.state[i]);net.fillStyle=value>.5?`rgba(255,199,126,${.3+value*.7})`:`rgba(112,211,191,${.15+value})`;net.beginPath();net.arc(p[0]*w,p[1]*h,1.5+value*1.3,0,Math.PI*2);net.fill();});$('gapSignal').textContent=Math.round(game.y-game.next().gapY)+' px';$('velocity').textContent=game.vy.toFixed(1);$('decision').textContent=brain.lastAction?'Aletear ↑':'Dejarse caer ↓';$('action').textContent=brain.lastAction?'↑ Impulso de las alas':'↓ Descenso';}
function drawChart(){const[w,h]=fit($('chart'),chart);chart.clearRect(0,0,w,h);const max=Math.max(5,...history.map(p=>p.test)),left=25,bottom=h-17;chart.font='9px Segoe UI';chart.textAlign='right';for(let k=0;k<3;k++){const value=max*k/2,y=bottom-(h-30)*k/2;chart.strokeStyle='#254053';chart.beginPath();chart.moveTo(left,y);chart.lineTo(w,y);chart.stroke();chart.fillStyle='#647e94';chart.fillText(value.toFixed(0),left-7,y+3);}chart.strokeStyle='#83d8ba';chart.lineWidth=2;chart.beginPath();const points=[{test:0},...history];points.forEach((p,i)=>{const x=left+i/(Math.max(points.length-1,10))*(w-left-5),y=bottom-p.test/max*(h-30);if(i===0)chart.moveTo(x,y);else chart.lineTo(x,y);});chart.stroke();chart.fillStyle='#6b8b9e';chart.textAlign='left';chart.fillText('generaciones →',left,h-2);}
function frame(now){const dt=Math.min(now-last||0,80);last=now;worldTime+=dt;acc+=dt*Number($('speed').value);let steps=0;while(acc>=1000/60&&steps<30){acc-=1000/60;steps++;if(game.alive){const action=game.frame%3===0?brain.act(game,activeWeights):false;game.step(action);if(game.score>record){record=game.score;$('record').textContent='Récord en pantalla: '+record;$('bestScore').textContent=record;}if(!game.alive)deadAt=now;}else{acc=0;if(now-deadAt>1100)newFlight();break;}}
drawGame(now);drawNetwork();drawChart();window.flappyState={ready:true,generation,episodes,training,baseline,score:game.score,frame:game.frame,flight,history,weights:best,activeWeights,lastReport};requestAnimationFrame(frame);}
requestAnimationFrame(frame);
})();
